from __future__ import annotations

from pathlib import Path


def write_slr_coeffs_header(
    *,
    out_path: Path,
    header_guard: str,
    intercept: float,
    coef: float,
) -> None:
    """
    Write a C header file with coefficients for a simple linear regression model:
      y = intercept + coef * x
    """
    out_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        f"#ifndef {header_guard}",
        f"#define {header_guard}",
        "",
        "// Auto-generated by mlaz.export.c_header",
        "// Model: y = intercept + coef * x",
        "",
        f"#define SLR_INTERCEPT              ({intercept:.15f})",
        f"#define SLR_COEF_YEARS_EXPERIENCE  ({coef:.11f})",
        "",
        f"#endif  // {header_guard}",
        "",
    ]

    out_path.write_text("\n".join(lines), encoding="utf-8")
