from __future__ import annotations

from pathlib import Path


def write_slr_coeffs_header(
    *,
    out_path: Path,
    header_guard: str,
    intercept: float,
    coef: float,
) -> None:
    """
    Write a C header file with coefficients for a simple linear regression model:
      y = intercept + coef * x
    """
    out_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        f"#ifndef {header_guard}",
        f"#define {header_guard}",
        "",
        "// Auto-generated by mlaz.export.c_header",
        "// Model: y = intercept + coef * x",
        "",
        f"#define SLR_INTERCEPT              ({intercept:.15f})",
        f"#define SLR_COEF_YEARS_EXPERIENCE  ({coef:.11f})",
        "",
        f"#endif  // {header_guard}",
        "",
    ]

    out_path.write_text("\n".join(lines), encoding="utf-8")


def write_mlr_coeffs_header(
    *,
    out_path: Path,
    header_guard: str,
    intercept: float,
    feature_names: list[str],
    coefs: list[float],
) -> None:
    """
    Write a C header for multiple linear regression:

      y = intercept + sum_i (coefs[i] * x[i])

    `feature_names` must match the coefficient order exactly.
    """
    if len(feature_names) != len(coefs):
        raise ValueError("feature_names and coefs must have the same length")

    out_path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = [
        f"#ifndef {header_guard}",
        f"#define {header_guard}",
        "",
        "// Auto-generated by mlaz.export.c_header",
        "// Model: y = intercept + sum_i (coef[i] * x[i])",
        "",
        f"#define MLR_INTERCEPT ({intercept:.15f})",
        "",
        f"#define MLR_NUM_FEATURES ({len(coefs)})",
        "",
        "static const char* MLR_FEATURE_NAMES[MLR_NUM_FEATURES] = {",
    ]

    for name in feature_names:
        safe = name.replace('"', '\\"')
        lines.append(f'    "{safe}",')

    lines += [
        "};",
        "",
        "static const double MLR_COEFS[MLR_NUM_FEATURES] = {",
    ]

    for c in coefs:
        lines.append(f"    {c:.15f},")

    lines += [
        "};",
        "",
        f"#endif  // {header_guard}",
        "",
    ]

    out_path.write_text("\n".join(lines), encoding="utf-8")
