#ifndef MLR_STARTUPS_MODEL_COEFFS_AUTOGEN_H
#define MLR_STARTUPS_MODEL_COEFFS_AUTOGEN_H

// Auto-generated by mlaz.export.c_header
// Model: y = intercept + sum_i (coef[i] * x[i])

#define MLR_INTERCEPT (54343.299848979535454)

#define MLR_NUM_FEATURES (6)

static const char* MLR_FEATURE_NAMES[MLR_NUM_FEATURES] = {
    "R&D Spend",
    "Administration",
    "Marketing Spend",
    "State_California",
    "State_Florida",
    "State_New York",
};

static const double MLR_COEFS[MLR_NUM_FEATURES] = {
    0.805630063715219,
    -0.068787882276830,
    0.029855442922689,
    -315.260255371806863,
    623.532750776629655,
    -308.272495404822962,
};

#endif  // MLR_STARTUPS_MODEL_COEFFS_AUTOGEN_H
