#ifndef SLR_SALARY_MODEL_COEFFS_AUTOGEN_H
#define SLR_SALARY_MODEL_COEFFS_AUTOGEN_H

// Auto-generated by mlaz.export.c_header
// Model: y = intercept + coef * x

#define SLR_INTERCEPT              (25321.583011776812782)
#define SLR_COEF_YEARS_EXPERIENCE  (9423.81532303098)

#endif  // SLR_SALARY_MODEL_COEFFS_AUTOGEN_H
